# Generated by Django 5.0.6 on 2024-05-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='problems',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['age']},
        ),
    ]
