# Generated by Django 5.0.6 on 2024-05-11 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_comments_options_alter_problems_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['id'], name='users_comme_id_c30fad_idx'),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['id'], name='users_probl_id_cebe67_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age'], name='users_userp_age_10a573_idx'),
        ),
    ]
