# Generated by Django 5.0.6 on 2024-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='listens',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
