# Generated by Django 5.0.6 on 2024-05-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_views_artist_page_views_song_listens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
    ]
