# Generated by Django 5.0.6 on 2024-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_bestsellers_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bestsellers',
            index=models.Index(fields=['id'], name='products_be_id_27cc43_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id'], name='products_ca_id_805265_idx'),
        ),
        migrations.AddIndex(
            model_name='featureditems',
            index=models.Index(fields=['id'], name='products_fe_id_5f7f85_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='products_pr_id_b46934_idx'),
        ),
    ]
