# Generated by Django 5.0.6 on 2024-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_bestsellers_products_be_id_27cc43_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsellers',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
